### ISSUE TITLE
感谢贡献以及一些疑问

### ISSUE THREAD

**Issue by specter119** [JunhuiJi/Chinese-Std-GB-T-7714-2005-numeric-Chinese#1]
我看了下你写的过程，应该也是以官方库里的7714-2005-numeric为蓝本开始写的吧？
写了这么多为啥不联系下作者更新给它呢，我觉得csl毕竟是开源的，讲道理原作者应该会直接加上你更新发布吧。

还有其实中文的最大的问题莫过于`等`和`et al`，有一个修改版本的zotero支持判断语言，它的国标见<https://github.com/Juris-M/jm-styles/blob/master/jm-chinese-gb7714-2005-numeric.csl>。

最后再次感谢贡献，我写毕业论文时候，可能把Juris-M的国标的轮子补好，到时候少不得参考你的csl。

**Comment by JunhuiJi** [comment]
首先感谢你的回复哈。
0. “7714-2015-numeric”我没找到……；
1. “我发布的csl是否原创”这个问题，基本语法当然是需要学习现有csl的，但是学习对象并不是你提到的“7714-2015-numeric”，毕竟学习csl的基本语法不需要考虑太多业务类型的东西（即参考文献的标准），而且我当时也没有7714-2015的标准可以参考。如果你指的是官方的“7714-2005-numeric”，把该版本和我的比较过后你应该能看到，对于文献条目的判断逻辑及实现方法是完全不同的；
2. 联系原作者这个事儿，你也提到了版本是2015的，而我写的是参照2005版本的标准，版本不同不应该混淆。如果你指的是官方的“7714-2005-numeric”，如上一条所述，不是更新的问题；
3. 感谢你告知有“判断语言”版本的csl存在。
再次感谢你的评论，也欢迎你把完成的轮子发布到官方（个人认为官方版的“chinese-gb7714-2005-numeric”是存在一些问题的，我曾经尝试过提交，但是官方在很久之后才要我提供与目前官方版本的优劣比较，然而我目前没有精力去做这个事儿了）。

**Comment by specter119** [comment]
口误，我是说官方的2005，已经改正，明白了，谢谢。

**Comment by menghuu** [comment]
@specter119 不知道有没有修改好？

**Comment by specter119** [comment]
@menghuu 你说 Juris-M 版的CSL吗，那个用的太少了，不准备弄了。建议用这个项目的 csl，等et al的问题用宏替换，宏的方法见 <https://zhuanlan.zhihu.com/p/53594081> 。
